### ISSUE TITLE
fork到自己仓库之后，如何部署到Github Page上。目前我这边会出现错误。

### ISSUE THREAD

**Issue by yuhanglee** [Lruihao/hugo-blog#108]
![image](https://github.com/Lruihao/hugo-blog/assets/34114647/502cbe7e-497a-4639-abc9-2c143cc0e8b3)

我将您这边的URL统一修改为我自己的仓库，在本地执行 `hugo server` 是可以通过访问 `localhost:1313` 查看。但是提交到仓库就不可以了。

期待您这边的回复。

如果不可以fork使用的话，请告知。

**Comment by Lruihao** [comment]
通过模板创建新的仓库

1. 点击 **Use this template**，在 GitHub 上创建你的存储库。

    <img width="913" alt="image" src="https://github.com/hugo-fixit/hugo-fixit-starter1/assets/33419593/d5fbd940-3ffd-4750-b1e6-4e87b50b0696">

2. 存储库创建后，克隆

    ```bash
    # 使用你自己的存储库 URL 进行克隆
    git clone --recursive https://github.com/<your_name>/<your_blog_repo>.git
    ```

3. 移除 private 子模块（这个是我的加密内容）

**Comment by Lruihao** [comment]
这个仓库有很多我本人的内容和定制化，建议通过以下两个模板之一快速开始：

- https://github.com/hugo-fixit/hugo-fixit-starter
- https://github.com/hugo-fixit/hugo-fixit-starter1

**Comment by yuhanglee** [comment]
感谢！！  通过看您的文章 [部署到Github](https://lruihao.cn/posts/github-actions/)，已经完成部署了，后续我自己再次修改部分内容。

也是看你这个仓库比较优秀，比较符合我目前的使用。   

再次感谢~~
