### ISSUE TITLE
【请教】hugo站内搜索方案

### ISSUE THREAD

**Issue by Zhang21** [Lruihao/hugo-blog#52]
作者你好，hugo的搜索有方案分享下么？我用原生的搜索效果太差了，又慢又不准确。

**Comment by Lruihao** [comment]
> 作者你好，hugo的搜索有方案分享下么？我用原生的搜索效果太差了，又慢又不准确。

用 [algolia](https://www.algolia.com/) 吧，[FixIt 支持的搜索引擎](https://fixit.lruihao.cn/theme-documentation-basics/#5-search)

**Comment by Lruihao** [comment]
> 这个每次都要上传json文件。请问，有没有简单点的呢？

使用 [atomic-algolia](https://github.com/chrisdmacrae/atomic-algolia) 创建一个 CI 每次更新源码自动上传 json

**Comment by Zhang21** [comment]
好的，谢谢作者。
