### ISSUE TITLE
文章页面访问量有时异常和代码显示行数不生效

### ISSUE THREAD

**Issue by Charlie-king** [Lruihao/hugo-blog#53]
经过一段时间的测试
发现文章页面访问量有时异常
无法加载
在config.toml中
valine开启了visitor，ibruce开启了enablePost
本地端正常
GitHub action部署上去就经常异常了
而我关掉ibruce，就正常了，怀疑了两个冲突了

代码显示行数不生效
文内代码块，设置默认显示行数不生效
短的话全部展开
长的话全部收缩

**Comment by Lruihao** [comment]
1. 不蒜子的访问量经常显示不了很正常，这是不蒜子的问题
2. 代码行数怎么设置的？

**Comment by Charlie-king** [comment]
[params.page.code]
# 是否显示代码块的复制按钮
copy = true
#  是否显示代码块的编辑按钮
edit = true
# 默认展开显示的代码行数
maxShownLines = 15

**Comment by Charlie-king** [comment]
```
[params.page.code]
# 是否显示代码块的复制按钮
copy = true
#  是否显示代码块的编辑按钮
edit = true
# 默认展开显示的代码行数
maxShownLines = 15
```

**Comment by Lruihao** [comment]
> ```
> 
> [params.page.code]
> 
> # 是否显示代码块的复制按钮
> 
> copy = true
> 
> #  是否显示代码块的编辑按钮
> 
> edit = true
> 
> # 默认展开显示的代码行数
> 
> maxShownLines = 15
> 
> ```

这样超过15行就折叠起来了，15行则展开的
